name: Build Game File
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Compile Game
        run: |
          # Compile to a single standalone file
          emcc main.cpp -o index.html \
          -s USE_SDL=2 \
          -s USE_SDL_IMAGE=2 \
          -s SDL2_IMAGE_FORMATS='["png","jpg"]' \
          -s SINGLE_FILE=1

      - name: Upload Single HTML File
        uses: actions/upload-artifact@v4
        with:
          name: my-game-html
          path: index.html
